version: "3.7"
services:
  url-shortener:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/url_shortener
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - url-shortener-network
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql"
    container_name: url-shortener-mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - url-shortener-network
    environment:
      MYSQL_DATABASE: url_shortener
      MYSQL_ROOT_PASSWORD: root
networks:
  url-shortener-network: