services:
  url-shortener:
    image: ${SERVICE_IMAGE_NAME}
    container_name: ${SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:${SERVICE_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${SCHEMA_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      CODE_LENGTH: ${CODE_LENGTH}
    networks:
      - url-shortener-network
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql"
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - "3306:${DB_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - url-shortener-network
    environment:
      MYSQL_DATABASE: ${SCHEMA_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
networks:
  url-shortener-network:
    driver: bridge